Add (./) codding style printing correctly w cs error 3

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -24,20 +24,18 @@ jobs:
         run: check.sh $(pwd) $(pwd)
       - name: Display coding style errors
         run: |
-          if [ -f coding-style-report.log ]; then
-            cat coding-style-report.log | while read line; do
-              part1=$(echo $line | cut -d: -f1)
-              part2=$(echo $line | cut -d: -f2)
-              part3=$(echo $line | cut -d: -f3)
-              title=$("coding style error")
-              error=$(echo $line | cut -d: -f4)
-              exit_code=1
-              echo -e "::error file=$part1 line=$part2, title=$title::$error_";
-            done < coding-style-report.log
-            if [ $exit_code -eq 1 ]
-            then
-              exit 1
-            fi
+          cat coding-style-report.log | while read line; do
+            part1=$(echo $line | cut -d: -f1)
+            part2=$(echo $line | cut -d: -f2)
+            part3=$(echo $line | cut -d: -f3)
+            title=$("coding style error")
+            error=$(echo $line | cut -d: -f4)
+            exit_code=1
+            echo "::error file=$part1 line=$part2, title=$title::$error_";
+          done < coding-style-report.log
+          if [ $exit_code -eq 1 ]
+          then
+            exit 1
           fi
 
   check_program_compilation_w_make:
